# fly.toml app configuration file
app = 'yaammoo-backend'
primary_region = 'cdg'

[build]

[env]
  NODE_ENV = "production"
  PORT = "3000"
  # Configuration SSL/TLS pour gRPC
  GRPC_SSL_CIPHER_SUITES = "ECDHE+AESGCM:ECDHE+CHACHA20:DHE+AESGCM:DHE+CHACHA20:!aNULL:!MD5:!DSS"
  NODE_TLS_REJECT_UNAUTHORIZED = "1"
  SSL_CERT_FILE = "/etc/ssl/certs/ca-certificates.crt"
  SSL_CERT_DIR = "/etc/ssl/certs"
  # Configuration Firebase/Firestore
  GOOGLE_CLOUD_PROJECT = ""
  GCLOUD_PROJECT = ""
  # Désactiver les émulateurs
  FIRESTORE_EMULATOR_HOST = ""
  FIREBASE_AUTH_EMULATOR_HOST = ""

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[deploy]
  release_command = "echo 'Deploying with gRPC support...'"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024

[experimental]
  auto_rollback = true
