# fly.toml app configuration file
app = 'yaammoo-backend'
primary_region = 'cdg'

[build]

[env]
  NODE_ENV = "production"
  GRPC_VERBOSITY = "ERROR"
  GRPC_TRACE = ""
  GRPC_SSL_CIPHER_SUITES = "HIGH+ECDSA"
  NODE_TLS_REJECT_UNAUTHORIZED = "1"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
